---
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        types: [python]
        entry: task lint:black --
      - id: isort
        name: isort
        language: system
        types: [python]
        entry: task lint:isort --
      - id: ruff
        name: ruff
        language: system
        types: [python]
        entry: task lint:ruff --
      - id: flake8
        name: flake8
        language: system
        types: [python]
        entry: task lint:flake8 --
