services:
  api:
    image: 'localhost/aap-eda'
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
    environment:
      EDA_DB_HOST: 'postgres'
    command:
      - /bin/bash
      - -c
      - django-admin migrate
        && django-admin runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - '../../:/app/src'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -q http://localhost:8000/_healthz
      interval: 30s
      timeout: 5s
      retries: 10

  postgres:
    image: 'docker.io/library/postgres:13'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eda
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: {}
